/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/atlas/algorithms": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Algorithms
         * @description Fichas verificadas do atlas de algoritmos (premissas, familia, referencias).
         */
        get: operations["list_algorithms_api_v1_atlas_algorithms_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/atlas/algorithms/{algorithm_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Algorithm */
        get: operations["get_algorithm_api_v1_atlas_algorithms__algorithm_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/atlas/ask": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ask
         * @description RAG local: trechos recuperados por TF-IDF; resposta do Ollama apenas com generate=true.
         */
        post: operations["ask_api_v1_atlas_ask_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/datasets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Datasets */
        get: operations["list_datasets_api_v1_datasets_get"];
        put?: never;
        /** Upload Dataset */
        post: operations["upload_dataset_api_v1_datasets_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/datasets/{dataset_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Dataset Details */
        get: operations["dataset_details_api_v1_datasets__dataset_id__get"];
        put?: never;
        post?: never;
        /** Delete Dataset */
        delete: operations["delete_dataset_api_v1_datasets__dataset_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/datasets/{dataset_id}/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Profile Dataset */
        post: operations["profile_dataset_api_v1_datasets__dataset_id__profile_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/methods": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Methods */
        get: operations["list_methods_api_v1_methods_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Runs */
        get: operations["list_runs_api_v1_runs_get"];
        put?: never;
        /**
         * Create Run
         * @description Pipeline robusto (ENSEMBLE_AUTO) sobre um dataset.
         */
        post: operations["create_run_api_v1_runs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/atlas-chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Atlas Chat
         * @description Selecao de metodos via chat local (Ollama), comparada ao filtro estatistico.
         */
        post: operations["create_atlas_chat_api_v1_runs_atlas_chat_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/atlas-experiment": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Atlas Experiment
         * @description Perfil -> metodos compativeis -> selecao cega -> avaliacao pos-hoc.
         */
        post: operations["create_atlas_experiment_api_v1_runs_atlas_experiment_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/benchmark": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Benchmark
         * @description Benchmark sintetico com ground truth conhecido + robustez a mudanca no regime de ruido.
         */
        post: operations["create_benchmark_api_v1_runs_benchmark_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/replicated-validation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Replicated Validation
         * @description Validacao estatistica pareada em replicas independentes (~5 min por replica).
         */
        post: operations["create_replicated_validation_api_v1_runs_replicated_validation_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Run */
        get: operations["get_run_api_v1_runs__run_id__get"];
        put?: never;
        post?: never;
        /** Delete Run */
        delete: operations["delete_run_api_v1_runs__run_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/result": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Result */
        get: operations["get_result_api_v1_runs__run_id__result_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AskRequest */
        AskRequest: {
            /**
             * Generate
             * @default false
             */
            generate: boolean;
            /**
             * K
             * @default 4
             */
            k: number;
            /** Model */
            model?: string | null;
            /** Query */
            query: string;
        };
        /** AtlasChatRequest */
        AtlasChatRequest: {
            /** Columns */
            columns?: string[] | null;
            /** Dataset Id */
            dataset_id: string;
            /** Declared Causal Sufficiency */
            declared_causal_sufficiency?: boolean | null;
            /**
             * Max Retries
             * @default 1
             */
            max_retries: number;
            /** Model */
            model?: string | null;
        };
        /** AtlasExperimentRequest */
        AtlasExperimentRequest: {
            /** Columns */
            columns?: string[] | null;
            /** Dataset Id */
            dataset_id: string;
            /** Declared Causal Sufficiency */
            declared_causal_sufficiency?: boolean | null;
            /**
             * Max Lag
             * @default 1
             */
            max_lag: number;
            /**
             * Max Methods
             * @default 3
             */
            max_methods: number | null;
            /** Max Rows */
            max_rows?: number | null;
            /** Methods */
            methods?: string[] | null;
            /**
             * N Bootstrap
             * @default 3
             */
            n_bootstrap: number;
            /**
             * Use Assumption Soft Filter
             * @default true
             */
            use_assumption_soft_filter: boolean;
        };
        /** BenchmarkRequest */
        BenchmarkRequest: {
            /**
             * Index Change
             * @default 250
             */
            index_change: number;
            /**
             * Max Lag
             * @default 2
             */
            max_lag: number;
            /** Methods */
            methods?: string[] | null;
            /**
             * N Bootstrap
             * @default 20
             */
            n_bootstrap: number;
            /**
             * N Samples
             * @default 500
             */
            n_samples: number;
            /**
             * Noise Multiplier
             * @default 3
             */
            noise_multiplier: number;
        };
        /** Body_upload_dataset_api_v1_datasets_post */
        Body_upload_dataset_api_v1_datasets_post: {
            /** Date Column */
            date_column?: string | null;
            /** File */
            file: string;
        };
        /** CreateRunRequest */
        CreateRunRequest: {
            /** Columns */
            columns?: string[] | null;
            /** Dataset Id */
            dataset_id: string;
            /** Decomposition Period */
            decomposition_period?: number | null;
            /**
             * Ensemble Threshold
             * @default 0.5
             */
            ensemble_threshold: number;
            /** Expert Knowledge */
            expert_knowledge?: components["schemas"]["ExpertRule"][];
            /**
             * Make Stationary
             * @default true
             */
            make_stationary: boolean;
            /**
             * Max Lag
             * @default 2
             */
            max_lag: number;
            /** Methods */
            methods?: string[] | null;
            /** N Bootstrap */
            n_bootstrap?: number | null;
            /**
             * Normalize
             * @default true
             */
            normalize: boolean;
            /** Objective */
            objective?: {
                [key: string]: unknown;
            } | null;
            /**
             * Panel Evidence
             * @default true
             */
            panel_evidence: boolean;
            /** Parallel Jobs */
            parallel_jobs?: number | null;
            /**
             * Quick Mode
             * @default false
             */
            quick_mode: boolean;
            /** Selected Relations */
            selected_relations?: [
                string,
                string
            ][] | null;
            /** Trajectory Index */
            trajectory_index?: number | null;
        };
        /** DatasetDetails */
        DatasetDetails: {
            /** Available Columns */
            available_columns: string[];
            /** Decomposition Period */
            decomposition_period: number | null;
            /** Default Max Lag */
            default_max_lag: number;
            entry: components["schemas"]["DatasetSummary"];
            /** Has Ground Truth */
            has_ground_truth: boolean;
            /** N Rows */
            n_rows: number;
            /** Preview */
            preview: {
                [key: string]: unknown;
            }[];
            /** Selected Columns */
            selected_columns: string[];
            /** Supports Replicates */
            supports_replicates: boolean;
            /** Trajectory Count */
            trajectory_count: number;
        };
        /** DatasetSummary */
        DatasetSummary: {
            /** Default Max Lag */
            default_max_lag: number;
            /** Description */
            description: string;
            /** Id */
            id: string;
            /** Name */
            name: string;
            /**
             * Origin
             * @enum {string}
             */
            origin: "builtin" | "upload";
        };
        /** ExpertRule */
        ExpertRule: {
            /**
             * Confidence
             * @default 0.5
             */
            confidence: number;
            /**
             * Constraint
             * @default soft
             * @enum {string}
             */
            constraint: "soft" | "hard";
            /** Lag */
            lag?: number | null;
            /** Prior Probability */
            prior_probability?: number | null;
            /**
             * Relation
             * @default weak
             * @enum {string}
             */
            relation: "strong" | "weak" | "inverse" | "none";
            /** Source */
            source: string;
            /** Target */
            target: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** MethodView */
        MethodView: {
            /** Default Weight */
            default_weight: number;
            /** Name */
            name: string;
        };
        /** ProfileRequest */
        ProfileRequest: {
            /** Columns */
            columns?: string[] | null;
            /** Declared Causal Sufficiency */
            declared_causal_sufficiency?: boolean | null;
        };
        /** ReplicatedValidationRequest */
        ReplicatedValidationRequest: {
            /** Columns */
            columns?: string[] | null;
            /** Dataset Id */
            dataset_id: string;
            /** Decomposition Period */
            decomposition_period?: number | null;
            /**
             * Ensemble Threshold
             * @default 0.5
             */
            ensemble_threshold: number;
            /**
             * Max Lag
             * @default 2
             */
            max_lag: number;
            /** Methods */
            methods?: string[] | null;
            /**
             * Min Confirmatory Replicates
             * @default 10
             */
            min_confirmatory_replicates: number;
            /**
             * Minimum Precision Gain
             * @default 0.05
             */
            minimum_precision_gain: number;
            /**
             * Minimum Win Rate
             * @default 0.7
             */
            minimum_win_rate: number;
            /** N Bootstrap */
            n_bootstrap?: number | null;
            /**
             * N Replicates
             * @default 10
             */
            n_replicates: number;
            /**
             * Quick Mode
             * @default false
             */
            quick_mode: boolean;
            /**
             * Replicate Seed
             * @default 2029
             */
            replicate_seed: number;
            /**
             * Significance Level
             * @default 0.05
             */
            significance_level: number;
            /**
             * Statistical Bootstraps
             * @default 10000
             */
            statistical_bootstraps: number;
        };
        /** RunView */
        RunView: {
            /** Created At */
            created_at: string;
            /** Error */
            error: string | null;
            /** Finished At */
            finished_at: string | null;
            /** Id */
            id: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "pipeline" | "benchmark" | "replicated_validation" | "atlas_experiment" | "atlas_chat";
            /** Params */
            params: {
                [key: string]: unknown;
            };
            /** Progress */
            progress: {
                [key: string]: unknown;
            } | null;
            /** Started At */
            started_at: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "queued" | "running" | "succeeded" | "failed" | "cancelled";
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_algorithms_api_v1_atlas_algorithms_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    }[];
                };
            };
        };
    };
    get_algorithm_api_v1_atlas_algorithms__algorithm_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                algorithm_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ask_api_v1_atlas_ask_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AskRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_datasets_api_v1_datasets_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DatasetSummary"][];
                };
            };
        };
    };
    upload_dataset_api_v1_datasets_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_dataset_api_v1_datasets_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DatasetSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    dataset_details_api_v1_datasets__dataset_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dataset_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DatasetDetails"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_dataset_api_v1_datasets__dataset_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dataset_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    profile_dataset_api_v1_datasets__dataset_id__profile_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dataset_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProfileRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    list_methods_api_v1_methods_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MethodView"][];
                };
            };
        };
    };
    list_runs_api_v1_runs_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunView"][];
                };
            };
        };
    };
    create_run_api_v1_runs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateRunRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_atlas_chat_api_v1_runs_atlas_chat_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AtlasChatRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_atlas_experiment_api_v1_runs_atlas_experiment_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AtlasExperimentRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_benchmark_api_v1_runs_benchmark_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BenchmarkRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_replicated_validation_api_v1_runs_replicated_validation_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReplicatedValidationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_run_api_v1_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_run_api_v1_runs__run_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_result_api_v1_runs__run_id__result_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
